### ISSUE TITLE
Release 1.3?

### ISSUE THREAD

**Issue by black-silence** [sunspikes/php-ratelimiter#13]
Hi, I'd like to use the moving window throttler in production but without a release tag I can't. Is the current master stable so you could push a new release to packagist?

**Comment by sunspikes** [comment]
@black-silence thank you for trying out the package! 

v1.2 has all the changes from master other than a README update and phpunit config fix, but anyway i have created an minor update release with the latest master v1.2.1, You can use this one.

**Comment by black-silence** [comment]
Thanks, now it works as expected.
